language: node_js
node_js:
  - '0.12'
services:
  - mongodb
script: "npm run-script test-travis"
before_script: "npm install lecle/managerservice lecle/httpservice lecle/logservice lecle/mongodbservice lecle/noservgatewayservice lecle/analyticsservice lecle/appsservice lecle/usersservice lecle/classesservice lecle/installationsservice lecle/filesservice lecle/pushservice lecle/authservice lecle/functionsservice lecle/scheduleservice lecle/rolesservice && mkdir public && mkdir public/files && mkdir logs"
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"
